### ISSUE TITLE
Clearer naming convention

### ISSUE THREAD

**Issue by Michael-A-Heuer** [makerdao/dss#122]
I suggest improving the naming of the contracts, methods, and variables.
This relates to an issue brought up by [Alex Van de Sande on Twitter](https://twitter.com/avsa/status/1204826528376401930?s=20)  and resulted in [a fork of this repository](https://github.com/alexvansande/MuchClearerDAI).

**Comment by ddaws** [comment]
I think the team has some strong opinions about this and I'm not sure it's productive to rehash this. I recommend checking out the annotated contracts. I think these are better than renaming and refactoring code because there is even more info there

https://docs.makerdao.com/other-documentation/smart-contract-annotations

For example, [here is the annotated Vat contract](https://via.hypothes.is/https://github.com/makerdao/dss/blob/master/src/vat.sol)

**Comment by gbalabasquer** [comment]
I understand reasons for liking or disliking this naming convention but certainly this is not an issue. We already know your position from the Twitter thread.

Code will not be renamed, between other reasons, because it is already deployed and integrated by partners this way. Renaming all of this at this stage would be crazy (even if we would agree with you).

As always, work done by the community, is really appreciated. Alex initiative was great. It is a nice parallel resource for those who prefer the other naming convention.

**Comment by hayeah** [comment]
if anyone arrives at this bike shed in the future and would like to build your own bike shed, here's a script to map DSS variables to your likings:

https://github.com/hayeah/dss/tree/rename#renaming
